/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VorotaRaspashnyeRouteImport } from './routes/vorota-raspashnye'
import { Route as VorotaOtkatnyeRouteImport } from './routes/vorota-otkatnye'
import { Route as ProflistRouteImport } from './routes/proflist'
import { Route as KalitkiRouteImport } from './routes/kalitki'
import { Route as JaluziRouteImport } from './routes/jaluzi'
import { Route as GitterRouteImport } from './routes/gitter'
import { Route as EvroshtaketnikRouteImport } from './routes/evroshtaketnik'
import { Route as DizainerskieRouteImport } from './routes/dizainerskie'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioSplatRouteImport } from './routes/studio/$'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'

const VorotaRaspashnyeRoute = VorotaRaspashnyeRouteImport.update({
  id: '/vorota-raspashnye',
  path: '/vorota-raspashnye',
  getParentRoute: () => rootRouteImport,
} as any)
const VorotaOtkatnyeRoute = VorotaOtkatnyeRouteImport.update({
  id: '/vorota-otkatnye',
  path: '/vorota-otkatnye',
  getParentRoute: () => rootRouteImport,
} as any)
const ProflistRoute = ProflistRouteImport.update({
  id: '/proflist',
  path: '/proflist',
  getParentRoute: () => rootRouteImport,
} as any)
const KalitkiRoute = KalitkiRouteImport.update({
  id: '/kalitki',
  path: '/kalitki',
  getParentRoute: () => rootRouteImport,
} as any)
const JaluziRoute = JaluziRouteImport.update({
  id: '/jaluzi',
  path: '/jaluzi',
  getParentRoute: () => rootRouteImport,
} as any)
const GitterRoute = GitterRouteImport.update({
  id: '/gitter',
  path: '/gitter',
  getParentRoute: () => rootRouteImport,
} as any)
const EvroshtaketnikRoute = EvroshtaketnikRouteImport.update({
  id: '/evroshtaketnik',
  path: '/evroshtaketnik',
  getParentRoute: () => rootRouteImport,
} as any)
const DizainerskieRoute = DizainerskieRouteImport.update({
  id: '/dizainerskie',
  path: '/dizainerskie',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSplatRoute = StudioSplatRouteImport.update({
  id: '/studio/$',
  path: '/studio/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/dizainerskie': typeof DizainerskieRoute
  '/evroshtaketnik': typeof EvroshtaketnikRoute
  '/gitter': typeof GitterRoute
  '/jaluzi': typeof JaluziRoute
  '/kalitki': typeof KalitkiRoute
  '/proflist': typeof ProflistRoute
  '/vorota-otkatnye': typeof VorotaOtkatnyeRoute
  '/vorota-raspashnye': typeof VorotaRaspashnyeRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/studio/$': typeof StudioSplatRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/dizainerskie': typeof DizainerskieRoute
  '/evroshtaketnik': typeof EvroshtaketnikRoute
  '/gitter': typeof GitterRoute
  '/jaluzi': typeof JaluziRoute
  '/kalitki': typeof KalitkiRoute
  '/proflist': typeof ProflistRoute
  '/vorota-otkatnye': typeof VorotaOtkatnyeRoute
  '/vorota-raspashnye': typeof VorotaRaspashnyeRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/studio/$': typeof StudioSplatRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/dizainerskie': typeof DizainerskieRoute
  '/evroshtaketnik': typeof EvroshtaketnikRoute
  '/gitter': typeof GitterRoute
  '/jaluzi': typeof JaluziRoute
  '/kalitki': typeof KalitkiRoute
  '/proflist': typeof ProflistRoute
  '/vorota-otkatnye': typeof VorotaOtkatnyeRoute
  '/vorota-raspashnye': typeof VorotaRaspashnyeRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/studio/$': typeof StudioSplatRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog'
    | '/dizainerskie'
    | '/evroshtaketnik'
    | '/gitter'
    | '/jaluzi'
    | '/kalitki'
    | '/proflist'
    | '/vorota-otkatnye'
    | '/vorota-raspashnye'
    | '/products/$productId'
    | '/studio/$'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalog'
    | '/dizainerskie'
    | '/evroshtaketnik'
    | '/gitter'
    | '/jaluzi'
    | '/kalitki'
    | '/proflist'
    | '/vorota-otkatnye'
    | '/vorota-raspashnye'
    | '/products/$productId'
    | '/studio/$'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog'
    | '/dizainerskie'
    | '/evroshtaketnik'
    | '/gitter'
    | '/jaluzi'
    | '/kalitki'
    | '/proflist'
    | '/vorota-otkatnye'
    | '/vorota-raspashnye'
    | '/products/$productId'
    | '/studio/$'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  DizainerskieRoute: typeof DizainerskieRoute
  EvroshtaketnikRoute: typeof EvroshtaketnikRoute
  GitterRoute: typeof GitterRoute
  JaluziRoute: typeof JaluziRoute
  KalitkiRoute: typeof KalitkiRoute
  ProflistRoute: typeof ProflistRoute
  VorotaOtkatnyeRoute: typeof VorotaOtkatnyeRoute
  VorotaRaspashnyeRoute: typeof VorotaRaspashnyeRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  StudioSplatRoute: typeof StudioSplatRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vorota-raspashnye': {
      id: '/vorota-raspashnye'
      path: '/vorota-raspashnye'
      fullPath: '/vorota-raspashnye'
      preLoaderRoute: typeof VorotaRaspashnyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vorota-otkatnye': {
      id: '/vorota-otkatnye'
      path: '/vorota-otkatnye'
      fullPath: '/vorota-otkatnye'
      preLoaderRoute: typeof VorotaOtkatnyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proflist': {
      id: '/proflist'
      path: '/proflist'
      fullPath: '/proflist'
      preLoaderRoute: typeof ProflistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalitki': {
      id: '/kalitki'
      path: '/kalitki'
      fullPath: '/kalitki'
      preLoaderRoute: typeof KalitkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jaluzi': {
      id: '/jaluzi'
      path: '/jaluzi'
      fullPath: '/jaluzi'
      preLoaderRoute: typeof JaluziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gitter': {
      id: '/gitter'
      path: '/gitter'
      fullPath: '/gitter'
      preLoaderRoute: typeof GitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evroshtaketnik': {
      id: '/evroshtaketnik'
      path: '/evroshtaketnik'
      fullPath: '/evroshtaketnik'
      preLoaderRoute: typeof EvroshtaketnikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dizainerskie': {
      id: '/dizainerskie'
      path: '/dizainerskie'
      fullPath: '/dizainerskie'
      preLoaderRoute: typeof DizainerskieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$': {
      id: '/studio/$'
      path: '/studio/$'
      fullPath: '/studio/$'
      preLoaderRoute: typeof StudioSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  DizainerskieRoute: DizainerskieRoute,
  EvroshtaketnikRoute: EvroshtaketnikRoute,
  GitterRoute: GitterRoute,
  JaluziRoute: JaluziRoute,
  KalitkiRoute: KalitkiRoute,
  ProflistRoute: ProflistRoute,
  VorotaOtkatnyeRoute: VorotaOtkatnyeRoute,
  VorotaRaspashnyeRoute: VorotaRaspashnyeRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  StudioSplatRoute: StudioSplatRoute,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
