/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProflistRouteImport } from './routes/proflist'
import { Route as JaluziRouteImport } from './routes/jaluzi'
import { Route as GitterRouteImport } from './routes/gitter'
import { Route as EvroshtaketnikRouteImport } from './routes/evroshtaketnik'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'

const ProflistRoute = ProflistRouteImport.update({
  id: '/proflist',
  path: '/proflist',
  getParentRoute: () => rootRouteImport,
} as any)
const JaluziRoute = JaluziRouteImport.update({
  id: '/jaluzi',
  path: '/jaluzi',
  getParentRoute: () => rootRouteImport,
} as any)
const GitterRoute = GitterRouteImport.update({
  id: '/gitter',
  path: '/gitter',
  getParentRoute: () => rootRouteImport,
} as any)
const EvroshtaketnikRoute = EvroshtaketnikRouteImport.update({
  id: '/evroshtaketnik',
  path: '/evroshtaketnik',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/evroshtaketnik': typeof EvroshtaketnikRoute
  '/gitter': typeof GitterRoute
  '/jaluzi': typeof JaluziRoute
  '/proflist': typeof ProflistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/evroshtaketnik': typeof EvroshtaketnikRoute
  '/gitter': typeof GitterRoute
  '/jaluzi': typeof JaluziRoute
  '/proflist': typeof ProflistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/evroshtaketnik': typeof EvroshtaketnikRoute
  '/gitter': typeof GitterRoute
  '/jaluzi': typeof JaluziRoute
  '/proflist': typeof ProflistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/evroshtaketnik'
    | '/gitter'
    | '/jaluzi'
    | '/proflist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalog' | '/evroshtaketnik' | '/gitter' | '/jaluzi' | '/proflist'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/evroshtaketnik'
    | '/gitter'
    | '/jaluzi'
    | '/proflist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  EvroshtaketnikRoute: typeof EvroshtaketnikRoute
  GitterRoute: typeof GitterRoute
  JaluziRoute: typeof JaluziRoute
  ProflistRoute: typeof ProflistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proflist': {
      id: '/proflist'
      path: '/proflist'
      fullPath: '/proflist'
      preLoaderRoute: typeof ProflistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jaluzi': {
      id: '/jaluzi'
      path: '/jaluzi'
      fullPath: '/jaluzi'
      preLoaderRoute: typeof JaluziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gitter': {
      id: '/gitter'
      path: '/gitter'
      fullPath: '/gitter'
      preLoaderRoute: typeof GitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evroshtaketnik': {
      id: '/evroshtaketnik'
      path: '/evroshtaketnik'
      fullPath: '/evroshtaketnik'
      preLoaderRoute: typeof EvroshtaketnikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  EvroshtaketnikRoute: EvroshtaketnikRoute,
  GitterRoute: GitterRoute,
  JaluziRoute: JaluziRoute,
  ProflistRoute: ProflistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
